// let a:string|number|undefined=10;
// let b:string|number|undefined=30;
// let c:string|number|undefined=60;
// let d:string|number|undefined=20;
var a = 10;
var b = 30;
var c = 60;
var d = 20;
console.warn(a);
console.warn(b);
console.warn(c);
